### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by dorignan** [majick777/autosave-net#2]
Hi,

I have this error when I activate the plugin: 

> Fatal error: Call to undefined function autosave_get_default_options() in plugins/autosave-net/autosave-net.php on line 202

It's possible that the call to the function "autosave_get_default_options" must be "autosave_net_default_options" ?

**Comment by majick777** [comment]
Quite correct, unfortunate typo there, have just pushed a hotfix. :-) thanks.
